use customer_shopping_behavior;
select * 
from customer;
SHOW COLUMNS FROM customer;

# Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,
       SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;


# Q2. Which customers used a discount but still spent more than the average purchase amount?
 SELECT customer_id,
       purchase_amount,
       discount_applied
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >
(
SELECT AVG(purchase_amount)
FROM customer
);

# Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
       AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

# Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
       AVG(purchase_amount) AS average_purchase
FROM customer
GROUP BY shipping_type;

# Q5. Do subscribed customers spend more? Compare average spend and total revenue 
# between subscribers and non-subscribers.
SELECT subscription_status,
       AVG(purchase_amount) AS average_spend,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

# Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(
SUM(CASE
WHEN discount_applied='Yes' THEN 1
ELSE 0
END)*100.0/COUNT(*),2
) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

# Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
 SELECT
CASE

WHEN previous_purchases = 0
THEN 'New'

WHEN previous_purchases BETWEEN 1 AND 5
THEN 'Returning'

ELSE 'Loyal'

END AS Customer_Segment,

COUNT(*) AS Total_Customers

FROM customer

GROUP BY Customer_Segment;

# Q8. What are the top 3 most purchased products within each category?
SELECT category,
       item_purchased,
       total_purchase
FROM
(
SELECT category,
       item_purchased,
       COUNT(*) AS total_purchase,
       DENSE_RANK() OVER
       (
       PARTITION BY category
       ORDER BY COUNT(*) DESC
       ) AS rnk
FROM customer
GROUP BY category,item_purchased
) t
WHERE rnk<=3;

# Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(*) AS total_customers
FROM customer
WHERE previous_purchases >5
GROUP BY subscription_status;

# Q10. What is the revenue contribution of each age group? 
SELECT
CASE
WHEN age BETWEEN 18 AND 25 THEN '18-25'

WHEN age BETWEEN 26 AND 35 THEN '26-35'

WHEN age BETWEEN 36 AND 45 THEN '36-45'

WHEN age BETWEEN 46 AND 55 THEN '46-55'

ELSE '56+'

END AS age_group,

SUM(purchase_amount) AS revenue

FROM customer

GROUP BY age_group

ORDER BY revenue DESC;